// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "call_me": Application Controllers
//
// Command:
// $ goagen
// --design=call_me/design
// --out=$(GOPATH)/src
// --version=v1.3.1

package app

import (
	"context"
	"github.com/goadesign/goa"
	"net/http"
)

// initService sets up the service encoders, decoders and mux.
func initService(service *goa.Service) {
	// Setup encoders and decoders
	service.Encoder.Register(goa.NewJSONEncoder, "application/json")
	service.Encoder.Register(goa.NewGobEncoder, "application/gob", "application/x-gob")
	service.Encoder.Register(goa.NewXMLEncoder, "application/xml")
	service.Decoder.Register(goa.NewJSONDecoder, "application/json")
	service.Decoder.Register(goa.NewGobDecoder, "application/gob", "application/x-gob")
	service.Decoder.Register(goa.NewXMLDecoder, "application/xml")

	// Setup default encoder and decoder
	service.Encoder.Register(goa.NewJSONEncoder, "*/*")
	service.Decoder.Register(goa.NewJSONDecoder, "*/*")
}

// CallMeController is the controller interface for the CallMe actions.
type CallMeController interface {
	goa.Muxer
	Dial(*DialCallMeContext) error
}

// MountCallMeController "mounts" a CallMe resource controller on the given service.
func MountCallMeController(service *goa.Service, ctrl CallMeController) {
	initService(service)
	var h goa.Handler

	h = func(ctx context.Context, rw http.ResponseWriter, req *http.Request) error {
		// Check if there was an error loading the request
		if err := goa.ContextError(ctx); err != nil {
			return err
		}
		// Build the context
		rctx, err := NewDialCallMeContext(ctx, req, service)
		if err != nil {
			return err
		}
		// Build the payload
		if rawPayload := goa.ContextRequest(ctx).Payload; rawPayload != nil {
			rctx.Payload = rawPayload.(*CallMePayLoad)
		} else {
			return goa.MissingPayloadError()
		}
		return ctrl.Dial(rctx)
	}
	service.Mux.Handle("GET", "/meet/:uid", ctrl.MuxHandler("dial", h, unmarshalDialCallMePayload))
	service.LogInfo("mount", "ctrl", "CallMe", "action", "Dial", "route", "GET /meet/:uid")
}

// unmarshalDialCallMePayload unmarshals the request body into the context request data Payload field.
func unmarshalDialCallMePayload(ctx context.Context, service *goa.Service, req *http.Request) error {
	payload := &callMePayLoad{}
	if err := service.DecodeRequest(req, payload); err != nil {
		return err
	}
	goa.ContextRequest(ctx).Payload = payload.Publicize()
	return nil
}
