// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "call_me": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=call_me/design
// --out=$(GOPATH)/src
// --version=v1.3.1

package app
