// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "call_me": call_me Resource Client
//
// Command:
// $ goagen
// --design=call_me/design
// --out=$(GOPATH)/src
// --version=v1.3.1

package client

import (
	"bytes"
	"context"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
)

// DialCallMePath computes a request path to the dial action of call_me.
func DialCallMePath(uid int) string {
	param0 := strconv.Itoa(uid)

	return fmt.Sprintf("/meet/%s", param0)
}

// DialCallMe makes a request to the dial action endpoint of the call_me resource
func (c *Client) DialCallMe(ctx context.Context, path string, payload *CallMePayLoad, contentType string) (*http.Response, error) {
	req, err := c.NewDialCallMeRequest(ctx, path, payload, contentType)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewDialCallMeRequest create the request corresponding to the dial action endpoint of the call_me resource.
func (c *Client) NewDialCallMeRequest(ctx context.Context, path string, payload *CallMePayLoad, contentType string) (*http.Request, error) {
	var body bytes.Buffer
	if contentType == "" {
		contentType = "*/*" // Use default encoder
	}
	err := c.Encoder.Encode(payload, &body, contentType)
	if err != nil {
		return nil, fmt.Errorf("failed to encode body: %s", err)
	}
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), &body)
	if err != nil {
		return nil, err
	}
	header := req.Header
	if contentType == "*/*" {
		header.Set("Content-Type", "application/json")
	} else {
		header.Set("Content-Type", contentType)
	}
	return req, nil
}
