// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "call_me": Application Media Types
//
// Command:
// $ goagen
// --design=call_me/design
// --out=$(GOPATH)/src
// --version=v1.3.1

package client

import "net/http"

// just say hi (default view)
//
// Identifier: application/vnd.call_me.bottle; view=default
type SayHiMedia struct {
	// my age
	MyAge *int `form:"my_age,omitempty" json:"my_age,omitempty" yaml:"my_age,omitempty" xml:"my_age,omitempty"`
	// my name
	MyName *string `form:"my_name,omitempty" json:"my_name,omitempty" yaml:"my_name,omitempty" xml:"my_name,omitempty"`
	// my phone no,call me now.
	MyPhone *string `form:"my_phone,omitempty" json:"my_phone,omitempty" yaml:"my_phone,omitempty" xml:"my_phone,omitempty"`
}

// DecodeSayHiMedia decodes the SayHiMedia instance encoded in resp body.
func (c *Client) DecodeSayHiMedia(resp *http.Response) (*SayHiMedia, error) {
	var decoded SayHiMedia
	err := c.Decoder.Decode(&decoded, resp.Body, resp.Header.Get("Content-Type"))
	return &decoded, err
}
