// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "call_me": Application User Types
//
// Command:
// $ goagen
// --design=call_me/design
// --out=$(GOPATH)/src
// --version=v1.3.1

package client

// callMePayLoad user type.
type callMePayLoad struct {
	// your age
	Age *int `form:"age,omitempty" json:"age,omitempty" yaml:"age,omitempty" xml:"age,omitempty"`
	// your gender, male or female
	Gender *string `form:"gender,omitempty" json:"gender,omitempty" yaml:"gender,omitempty" xml:"gender,omitempty"`
	// your name
	Name *string `form:"name,omitempty" json:"name,omitempty" yaml:"name,omitempty" xml:"name,omitempty"`
	// your phone no.
	PhoneNo *string `form:"phone_no,omitempty" json:"phone_no,omitempty" yaml:"phone_no,omitempty" xml:"phone_no,omitempty"`
}

// Publicize creates CallMePayLoad from callMePayLoad
func (ut *callMePayLoad) Publicize() *CallMePayLoad {
	var pub CallMePayLoad
	if ut.Age != nil {
		pub.Age = ut.Age
	}
	if ut.Gender != nil {
		pub.Gender = ut.Gender
	}
	if ut.Name != nil {
		pub.Name = ut.Name
	}
	if ut.PhoneNo != nil {
		pub.PhoneNo = ut.PhoneNo
	}
	return &pub
}

// CallMePayLoad user type.
type CallMePayLoad struct {
	// your age
	Age *int `form:"age,omitempty" json:"age,omitempty" yaml:"age,omitempty" xml:"age,omitempty"`
	// your gender, male or female
	Gender *string `form:"gender,omitempty" json:"gender,omitempty" yaml:"gender,omitempty" xml:"gender,omitempty"`
	// your name
	Name *string `form:"name,omitempty" json:"name,omitempty" yaml:"name,omitempty" xml:"name,omitempty"`
	// your phone no.
	PhoneNo *string `form:"phone_no,omitempty" json:"phone_no,omitempty" yaml:"phone_no,omitempty" xml:"phone_no,omitempty"`
}
